
language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -udroguedozed@gmail.com
    on_success: never # default: change
    on_failure: always # default: always